first pr to provide basic systemd runtime functions
projecteru2/systemd-runtime pull request #4
Opened 2021-06-06 20:23 UTC by nyanpassu

This pr is meant to initalize the project and provide a basic implementation of systemd runtime.

What I did:
1. A custom platform runtime forked from containerd to provide management of systemd shim processes.
2. A custom containerd binary to make using the custom platform runtime specified in container possible.
3. A custom shim runtime to make shim process init by systemd

2021-09-24 09:02 UTC, jschwinger23 commented
自测用例:

1. docker run -d --name app_entry_xxx bash sleep 10000 (默认网络是 host?)
2. docker stop, docker stop -t, docker rm, docker rm -f, docker restart
3. 资源: docker run --cpu-shares --cpuset-cpus --cpuset-mems --memory-bytes; volume 支持吗?
4. 文件: docker cp, 双向
5. docker exec, 你可能不支持 tty, 所以 docker exec xxx ls
6. docker inspect
7. docker ps, docker stats
8. docker logs? docker attach?
9. 资源动态调整: docker update
10. 事件: docker events

除了上述 API 的可用性, 还要测试异常情况, 比如故意创建一个起不来的容器: docker run -d bash xxx, 或者立刻结束的: docker run -d bash ls, 容器自动无限重启, 等等.

要观察各种副作用, 进程状态是否正常(僵尸, 孤儿, 残留), 文件是否清理干净, 关联状态是否正确(containerd 和 dockerd 自己的元数据), docker 会创建网络相关数据吗, 资源限制在 OS 上的绑定正确吗, 等等.

最后再来测试和 eru 的集成, 通过 eru-cli 去测试, eru-cli workload 这些就不说了.

另外要考虑 eru-agent 的跟进, 上报 systemd app 的状态给 eru.

2021-10-21 10:28 UTC, jschwinger233 commented
第一次功能 review 查出了这些问题:

1. run -it --rm 永久阻塞, 命令 `/usr/bin/docker -H unix:///var/run/eru/docker.sock run -it --rm --runtime io.containerd.eru.v2 bash bash`
2. 强杀 (kill -9) shim 进程导致容器进程变成孤儿
3. 强杀容器进程导致 shim 进程残留
4. docker restart 报错: `mkdir /run/eru/containerd/io.containerd.runtime.v1.io.containerd.eru.v2/io.containerd.eru.v2/e51c0582aa70db5e08aa0dad0d18226c2836f312d66a1278e6026acf6c3909a9: file exists: unknown`
5. exec 进程被 ctrl-c 打断后, 新创建的进程依然残留
6. systemctl restart eru-systemd-$id 直接阻塞, 容器是 bash, 命令是 sleep 10000
7. --restart always 没有生效, 重启电脑后没有被自动拉起来, 甚至手动也无法拉起来

2021-10-28 09:01 UTC, jschwinger233 commented
第二轮功能 review:

1. systemctl stop 太慢, 耗时一分半
2. Exchange 在重启之后没有初始化
3. docker kill -s 1 之后再 kill -9 会导致状态变成 exited 而不是 paused
4. docker run -d --rm 在容器在重启 dockerd + containerd 之后被删除
5. docker logs 不能用
6. docker attach 不能用
7. dockerd / containerd 死掉的时候, systemctl stop 服务, 之后 docker 看到的容器状态始终是 running 且不再生成 events

2021-11-01 09:58 UTC, nyanpassu commented
> 第二轮功能 review:
> 
> 1. systemctl stop 太慢, 耗时一分半
> 2. Exchange 在重启之后没有初始化
> 3. docker kill -s 1 之后再 kill -9 会导致状态变成 exited 而不是 paused
> 4. docker run -d --rm 在容器在重启 dockerd + containerd 之后被删除
> 5. docker logs 不能用
> 6. docker attach 不能用
> 7. dockerd / containerd 死掉的时候, systemctl stop 服务, 之后 docker 看到的容器状态始终是 running 且不再生成 events

除了logs和attach以及--rm，其他已经修复
--rm，attach支持有困难，在systemd runtime中也用不到，可以不支持
logs会继续考虑支持方法

2021-11-12 10:15 UTC, jschwinger233 commented
我们又高强度对线了一轮, 新发现的问题是 exec(2) 的报错没有让 dockerd 直接呈报回去, 其他的感觉都还好, 当前功能(除了日志)应该已经符合 calico, eru-agent, barrel 的部署要求了, 可以在 87 上部署试试看.
楼主说这个月完成 docker logs 的功能, 然后下个月上 nonlive.

2021-11-12 10:20 UTC, jschwinger233 commented
为啥始终是一个 commit, 而且时间一直是 Apr 22?

2021-11-12 10:31 UTC, nyanpassu commented
> 为啥始终是一个 commit, 而且时间一直是 Apr 22?

感觉是git detech header的问题，我整整

2021-11-15 11:00 UTC, jschwinger233 reviewed
整体还是有可读性的, 逻辑也比想象中的顺畅. 
不过 kill -9 容器进程, 容器变成 paused, 这个逻辑是在哪里处理的? 没有看到 SIGCHLD 有特别的处理.

2021-11-15 11:00 UTC, jschwinger233 commented on shim/ctnholder.go
> +	locker := h.mu.RLocker()
这个好像直接 h.mu.RLock() 就可以了吧

2021-11-15 11:00 UTC, jschwinger233 commented on shim/ctnholder.go
> +		locker.Unlock()
return xxx, h.mu.RUnlock

2021-11-15 11:00 UTC, jschwinger233 commented on shim/shim.go
> +func (s *Service) Serve(ctx context.Context, sigChan <-chan uint32) (err error) {
这个 sigChan 其实只会吐出来 15 对吧, 那可以换个更准确的名字

2021-11-15 11:00 UTC, jschwinger233 commented on shim/shim.go
> +	_, err = s.serveTaskService(s.logger)
话说这个 serveTaskService 不需要传递 ctx 吗

2021-11-15 11:00 UTC, jschwinger233 commented on shim/shim.go
> +	evt, err := s.createContainer(ctx, opts)
我有一个小问题, 为什么在 init 的时候就 runc create, 而不是在 TaskService.Create?

2021-11-15 11:00 UTC, jschwinger233 commented on shim/shim.go
> +			if err := s.killContainer(ns.WithNamespace(context.Background(), s.namespace), sig); err != nil {
有做 graceful term 吗?没有看到- -

2021-11-15 11:00 UTC, jschwinger233 commented on cmd/eru-systemd-shim/shim/shim.go
> +	if !s.config.NoReaper {
这个 NoReaper 会有地方用到吗

2021-11-15 11:00 UTC, jschwinger233 commented on cmd/eru-systemd-shim/shim/shim.go
> +		if publisher.signalSet {
这个 signalSet 是干嘛的

2021-11-15 11:21 UTC, rivetcat commented
> 整体还是有可读性的, 逻辑也比想象中的顺畅. 不过 kill -9 容器进程, 容器变成 paused, 这个逻辑是在哪里处理的? 没有看到 SIGCHLD 有特别的处理.

这个是在task connection manager里。shim进程被杀死后，ttrpc的conn中断，conn manager会尝试再次连接。连接之前会先check bundle的状态，如果没有在运行会发paused event，同时做cleanup，cleanup是尝试把泄露的container进程干掉。
sigchild肯定处理不了这个情况啦。

2021-11-15 11:27 UTC, jschwinger233 commented
我怎么看到是 service 有个后台 goroutine `go s.processExits()`, 里面在 checkProcesses 然后 SendEventPaused?

2021-11-15 11:29 UTC, jschwinger233 commented
明白了, 我大意了, 这个逻辑已经很大部分封装到了 container/reaper 里, reaper.Default.Subscribe()就是进程退出事件 chan; 所以我说用 SIGCHLD 倒是没错...

2021-11-15 11:30 UTC, jschwinger233 commented
看到你没有重新造这部分的轮子真是欣慰....

2021-11-16 02:11 UTC, nyanpassu commented on cmd/eru-systemd-shim/shim/shim.go
> +	if !s.config.NoReaper {
我们应该用不到，是containerd shim原来的东西，先留着吧，之后叠代再去掉 =。=

2021-11-16 02:13 UTC, rivetcat commented on shim/shim.go
> +	evt, err := s.createContainer(ctx, opts)
因为shim是自启动的不是等containerd task manager把它拉起来，所以要在init的时候就create。TaskService.Create实际上不会从shim去调用了。

2021-11-16 02:16 UTC, nyanpassu commented on shim/shim.go
> +	_, err = s.serveTaskService(s.logger)
不用，它里面会启动一个goroutine跑ttrpc service，但不需要context参数。ttrpc service提供一个shutdown方法，我通过serveTaskSerivce返回了，但是也没有调用价值。shim退出的时候就自动关了，就先ignore了。containerd shim在这里的入参context只是拿来获取logger的。

2021-11-16 02:20 UTC, nyanpassu commented on shim/ctnholder.go
> +		locker.Unlock()
fixed

2021-11-16 02:26 UTC, nyanpassu commented on shim/ctnholder.go
> +	locker := h.mu.RLocker()
fixed

2021-11-16 02:28 UTC, nyanpassu commented on shim/shim.go
> +func (s *Service) Serve(ctx context.Context, sigChan <-chan uint32) (err error) {
fixed

2021-11-16 02:29 UTC, nyanpassu commented on shim/shim.go
> +			if err := s.killContainer(ns.WithNamespace(context.Background(), s.namespace), sig); err != nil {
在startService部分（改名叫runService好了），service.Serve结束后做了cleanup。

2021-11-16 02:38 UTC, nyanpassu commented on cmd/eru-systemd-shim/shim/shim.go
> +		if publisher.signalSet {
是表示struct里的signal是一个有效的value，已经改成了更有意义的表示。

2021-11-16 06:44 UTC, jschwinger233 commented on cmd/eru-systemd-shim/shim/shim.go
> +		close(sub)
为什么只推一个信号就退了？

2021-11-16 06:47 UTC, jschwinger233 requested changes
信号有比较大的问题， 没有 graceful term 的逻辑，比如给 shim 发 15，shim 的退出逻辑应该是先转发 15 给容器进程，然后等一段时间（一般 30s）后发送 9 强杀。

2021-11-16 08:00 UTC, nyanpassu commented on cmd/eru-systemd-shim/shim/shim.go
> +		close(sub)
因为这里是订阅，订阅方对信号的期望是exactly once。

2021-11-16 08:05 UTC, nyanpassu commented
> 信号有比较大的问题， 没有 graceful term 的逻辑，比如给 shim 发 15，shim 的退出逻辑应该是先转发 15 给容器进程，然后等一段时间（一般 30s）后发送 9 强杀。

我觉得我们不用处理这个其实，dockerd和systemd都有处理term超时的逻辑，containerd shim也没做这个事情。人工发送信号其实是不建议的方式，超时了也可以人工kill。

2021-11-16 09:07 UTC, jschwinger233 commented
> 我觉得我们可以先不处理这个其实

好

2021-11-16 09:13 UTC, jschwinger233 approved these changes

2021-11-16 11:10 UTC, merged