[bugfix]exec stdio forwarding fix
projecteru2/systemd-runtime pull request #6
Opened 2022-01-13 17:35 UTC by nyanpassu

In this pr, the stdio fowarding of exec is fixed.

The bug is caused by closing of direct io is early then fifo open. The previous version will close fifo when direct io is closed(by io.Copy encounted end of io stream from container exec process), so the content in buffer will not be written to fifo. In this version the buffer will be checked on closing, if the buffer has content, the fifo will not be closed instantly and will be closed when all content has been written to fifo.

2022-01-17 08:12 UTC, jschwinger233 commented
```
ERRO[2022-01-17T16:11:37.833089490+08:00] stream copy error: failed to open /var/run/eru/docker/containerd/c981ff937242bfd6a76983364f94b707db3927fd98ec3258affe958efc06b5f2/init-stdout with O_PATH: open /var/run/eru/docker/containerd/c981ff937242bfd6a76983364f94b707db3927fd98ec3258affe958efc06b5f2/init-stdout: too many open files 
2022-01-17 16:11:48.809809 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 5ms
2022-01-17 16:11:48.814976 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 10ms
2022-01-17 16:11:48.825216 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 20ms
2022-01-17 16:11:48.845398 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 40ms
2022-01-17 16:11:48.885604 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 80ms
2022-01-17 16:11:48.965937 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 160ms
2022-01-17 16:11:49.126208 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 320ms
2022-01-17 16:11:49.446479 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 640ms
2022-01-17 16:11:50.086694 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 1s
2022-01-17 16:11:51.086949 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 1s
2022-01-17 16:11:52.087330 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 1s
2022-01-17 16:11:53.087622 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 1s
2022-01-17 16:11:54.087888 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 1s
2022-01-17 16:11:55.088170 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 1s
2022-01-17 16:11:56.088596 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 1s
2022-01-17 16:11:57.088861 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 1s
2022-01-17 16:11:58.089188 I | http: Accept error: accept unix /var/run/eru/docker.sock: accept4: too many open files; retrying in 1s
```

2022-01-17 08:20 UTC, jschwinger233 commented
启动 dockerd:

```
ERRO[2022-01-17T16:20:05.501658351+08:00] stream copy error: failed to open /var/run/eru/docker/containerd/c981ff937242bfd6a76983364f94b707db3927fd98ec3258affe958efc06b5f2/init-stdout with O_PATH: open /var/run/eru/docker/containerd/c981ff937242bfd6a76983364f94b707db3927fd98ec3258affe958efc06b5f2/init-stdout: too many open files 
failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables --wait -t nat -N DOCKER:  (pipe2: too many open files)
```

2022-01-17 08:22 UTC, jschwinger233 commented
还是启动 dockerd:

```
f365aaa5215ba941efd7e7d07972a9904b88224da50f4e37dddec090 error="failed to create default sandbox: namespace creation reexec command failed: fork/exec /proc/self/exe: too many open files"
INFO[2022-01-17T16:21:47.284777555+08:00] Loading containers: done.                    
WARN[2022-01-17T16:21:47.288250115+08:00] failed to retrieve runc version: pipe2: too many open files 
WARN[2022-01-17T16:21:47.288536764+08:00] failed to retrieve docker-init version: pipe2: too many open files 
WARN[2022-01-17T16:21:47.294944953+08:00] Failed to remove check directory /var/lib/eru/docker/overlay2/opaque-bug-check045290644: openfdat /var/lib/eru/docker/overlay2/opaque-bug-check045290644/l3/d: too many open files  storage-driver=overlay2
INFO[2022-01-17T16:21:47.295176290+08:00] Docker daemon                                 commit=c46ad7d8dc graphdriver(s)=overlay2 version=dev
INFO[2022-01-17T16:21:47.295261617+08:00] Daemon has completed initialization          
failed to open database file /var/lib/eru/docker/buildkit/cache.db: open /var/lib/eru/docker/buildkit/cache.db: too many open files
```

2022-01-17 08:25 UTC, jschwinger233 commented
运行一个容器:

```
/usr/bin/docker -H unix:///var/run/eru/docker.sock run -d --runtime io.containerd.eru.v2 --net host bash bash -c 'while :; do date; done'
```

然后去看 dockerd 的 fd:

```
$ lsof -p $(pidof dockerd)
COMMAND     PID USER   FD      TYPE             DEVICE SIZE/OFF       NODE NAME
dockerd 1622959 root  cwd       DIR              259,2     4096    2626428 /home/gray/Dropbox/mac.local/Documents/src/github.com/projecteru2/moby
dockerd 1622959 root  rtd       DIR              259,2     4096          2 /
dockerd 1622959 root  txt       REG              259,2 78979792    2753701 /home/gray/Dropbox/mac.local/Documents/src/github.com/projecteru2/moby/bundles/binary-daemon/dockerd-dev
dockerd 1622959 root  mem-W     REG              259,2    32768   24913268 /var/lib/eru/docker/buildkit/cache.db
dockerd 1622959 root  mem-W     REG              259,2    16384   24913262 /var/lib/eru/docker/buildkit/metadata_v2.db
dockerd 1622959 root  mem-W     REG              259,2    16384   24913261 /var/lib/eru/docker/buildkit/snapshots.db
dockerd 1622959 root  mem-W     REG              259,2    16384   24913260 /var/lib/eru/docker/buildkit/containerdmeta.db
dockerd 1622959 root  mem-W     REG              259,2    32768   24913210 /var/lib/eru/docker/volumes/metadata.db
dockerd 1622959 root    0u      CHR              136,7      0t0         10 /dev/pts/7
dockerd 1622959 root    1u      CHR              136,7      0t0         10 /dev/pts/7
dockerd 1622959 root    2u      CHR              136,7      0t0         10 /dev/pts/7
dockerd 1622959 root    3u     unix 0xffff8cfb2b43f800      0t0   16102650 @0006b type=DGRAM
dockerd 1622959 root    4u  a_inode               0,13        0      12186 [eventpoll]
dockerd 1622959 root    5u     unix 0xffff8cfb2b43e000      0t0   16102651 type=DGRAM
dockerd 1622959 root    6u     unix 0xffff8cfb2b438000      0t0   16102653 /var/run/eru/docker.sock type=STREAM
dockerd 1622959 root    7u     unix 0xffff8cfa35d34000      0t0   16098074 /var/run/eru/docker/metrics.sock type=STREAM
dockerd 1622959 root    8u     unix 0xffff8cfa35d37c00      0t0   16098075 type=STREAM
dockerd 1622959 root    9u     unix 0xffff8cf979e03c00      0t0   16097038 type=STREAM
dockerd 1622959 root   10uW     REG              259,2    32768   24913210 /var/lib/eru/docker/volumes/metadata.db
dockerd 1622959 root   11w      REG              259,2        0   27686716 /var/lib/eru/docker/containers/33616f0cdb9a55733a72d33fe79263f04bada800235e71eacb3177a080379036/33616f0cdb9a55733a72d33fe79263f04bada800235e71eacb3177a080379036-json.log
dockerd 1622959 root   12w      REG              259,2        0   24917114 /var/lib/eru/docker/containers/6a4b50955408901bd229cad7dd95fec1a55290a5fc75331600e0bc3b2f4bb91d/6a4b50955408901bd229cad7dd95fec1a55290a5fc75331600e0bc3b2f4bb91d-json.log
dockerd 1622959 root   13r      REG                0,4        0 4026532008 net
dockerd 1622959 root   14u  netlink                         0t0   16096127 ROUTE
dockerd 1622959 root   15u  netlink                         0t0   16096128 XFRM
dockerd 1622959 root   16w      REG              259,2   448831   25056752 /var/lib/eru/docker/containers/c981ff937242bfd6a76983364f94b707db3927fd98ec3258affe958efc06b5f2/c981ff937242bfd6a76983364f94b707db3927fd98ec3258affe958efc06b5f2-json.log
dockerd 1622959 root   17u     FIFO               0,25      0t0       1206 /run/eru/docker/containerd/c981ff937242bfd6a76983364f94b707db3927fd98ec3258affe958efc06b5f2/init-stderr
dockerd 1622959 root   18u  netlink                         0t0   16096129 NETFILTER
dockerd 1622959 root   19u     unix 0xffff8cfb27328400      0t0   16096147 /var/run/eru/docker/libnetwork/c34e2cfc8c45.sock type=STREAM
dockerd 1622959 root   20u     FIFO               0,25      0t0       1415 /run/eru/docker/containerd/26320a92e087c273cbeb942ed665cf8f78b80eeb2fc197d0b9b3e4ee8b5500b1/init-stdout (deleted)
dockerd 1622959 root   21uW     REG              259,2    16384   24913260 /var/lib/eru/docker/buildkit/containerdmeta.db
dockerd 1622959 root   22w      REG              259,2        0   24908094 /var/lib/eru/docker/containers/b6e25791e809c7caff27de575add2984ec43b3bddbdc657b246cec3ed5efbfdb/b6e25791e809c7caff27de575add2984ec43b3bddbdc657b246cec3ed5efbfdb-json.log
dockerd 1622959 root   23u     FIFO               0,25      0t0       1403 /run/eru/docker/containerd/62688dd1f365aaa5215ba941efd7e7d07972a9904b88224da50f4e37dddec090/init-stdout (deleted)
dockerd 1622959 root   24u     FIFO               0,25      0t0       1203 /run/eru/docker/containerd/c981ff937242bfd6a76983364f94b707db3927fd98ec3258affe958efc06b5f2/init-stdout
dockerd 1622959 root   27u  netlink                         0t0   16102810 ROUTE
dockerd 1622959 root   28u     FIFO               0,25      0t0       1404 /run/eru/docker/containerd/62688dd1f365aaa5215ba941efd7e7d07972a9904b88224da50f4e37dddec090/init-stderr (deleted)
dockerd 1622959 root   31u     FIFO               0,25      0t0       1406 /run/eru/docker/containerd/990e52bb738aaadca70323051dd3346059d344c0c74c05e7cfc4bc3bdbee35fd/init-stdout (deleted)
dockerd 1622959 root   34u     FIFO               0,25      0t0       1407 /run/eru/docker/containerd/990e52bb738aaadca70323051dd3346059d344c0c74c05e7cfc4bc3bdbee35fd/init-stderr (deleted)
dockerd 1622959 root   36u     FIFO               0,25      0t0       1411 /run/eru/docker/containerd/b268fd9d52c7f0e66167ed93fc004734290b69b4120b47799135bdc46f41110c/init-stdout (deleted)
dockerd 1622959 root   37u     FIFO               0,25      0t0       1409 /run/eru/docker/containerd/bc67a74564386587d2441ab04765a9003ac0662a1c6342155f1e03b289e863ed/init-stderr (deleted)
dockerd 1622959 root   39u     FIFO               0,25      0t0       1412 /run/eru/docker/containerd/b268fd9d52c7f0e66167ed93fc004734290b69b4120b47799135bdc46f41110c/init-stderr (deleted)
dockerd 1622959 root   40u     FIFO               0,25      0t0       1408 /run/eru/docker/containerd/bc67a74564386587d2441ab04765a9003ac0662a1c6342155f1e03b289e863ed/init-stdout (deleted)
dockerd 1622959 root   42u     FIFO               0,25      0t0       1416 /run/eru/docker/containerd/26320a92e087c273cbeb942ed665cf8f78b80eeb2fc197d0b9b3e4ee8b5500b1/init-stderr (deleted)
dockerd 1622959 root   46uW     REG              259,2    16384   24913261 /var/lib/eru/docker/buildkit/snapshots.db
dockerd 1622959 root   47uW     REG              259,2    16384   24913262 /var/lib/eru/docker/buildkit/metadata_v2.db
dockerd 1622959 root   48uW     REG              259,2    32768   24913268 /var/lib/eru/docker/buildkit/cache.db
dockerd 1622959 root   49u     FIFO               0,25      0t0       1397 /run/eru/docker/containerd/1f16562c34b31035447ee9548ec57ee2d38e1e7563cb4c2d68bac208a6d95449/init-stdout
dockerd 1622959 root   50r     FIFO               0,25      0t0       1397 /run/eru/docker/containerd/1f16562c34b31035447ee9548ec57ee2d38e1e7563cb4c2d68bac208a6d95449/init-stdout
dockerd 1622959 root   51u     FIFO               0,25      0t0       1397 /run/eru/docker/containerd/1f16562c34b31035447ee9548ec57ee2d38e1e7563cb4c2d68bac208a6d95449/init-stdout
dockerd 1622959 root   52u     FIFO               0,25      0t0       1398 /run/eru/docker/containerd/1f16562c34b31035447ee9548ec57ee2d38e1e7563cb4c2d68bac208a6d95449/init-stderr
dockerd 1622959 root   53r     FIFO               0,25      0t0       1397 /run/eru/docker/containerd/1f16562c34b31035447ee9548ec57ee2d38e1e7563cb4c2d68bac208a6d95449/init-stdout
dockerd 1622959 root   54r     FIFO               0,25      0t0       1398 /run/eru/docker/containerd/1f16562c34b31035447ee9548ec57ee2d38e1e7563cb4c2d68bac208a6d95449/init-stderr
dockerd 1622959 root   55w      REG              259,2    90381   25835880 /var/lib/eru/docker/containers/1f16562c34b31035447ee9548ec57ee2d38e1e7563cb4c2d68bac208a6d95449/1f16562c34b31035447ee9548ec57ee2d38e1e7563cb4c2d68bac208a6d95449-json.log
dockerd 1622959 root   56u     FIFO               0,25      0t0       1397 /run/eru/docker/containerd/1f16562c34b310354 [...]

2022-01-17 08:27 UTC, jschwinger233 requested changes
dockerd fd 泄露

2022-01-26 16:49 UTC, nyanpassu commented
> lsof -p $(pidof dockerd)

确认是dockerd那边的问题了，和shim没关系。。。

2022-02-10 08:07 UTC, jschwinger233 approved these changes

2022-02-10 08:29 UTC, merged